### ISSUE TITLE
division by zero error

### ISSUE THREAD

**Issue by mr-flibble** [jsoares/ttrss-plugin-feedstatistics#1]
Hello, yesterday I noticed that Statistics are empty. The system log items are:

Error: E_USER_ERROR (256)
Filename:classes/db/pgsql.php:46

Message: 
Query SELECT ttrss_feeds.title as feed, ttrss_feed_categories.title as category, COUNT(ref_id) as items, COUNT(NULLIF(marked, false)) as starred, COUNT(NULLIF(published, false)) AS published, ROUND(CAST(COUNT(ref_id) AS DECIMAL)/0,2) as items_day FROM ttrss_feeds LEFT JOIN ttrss_user_entries ON ttrss_feeds.id = ttrss_user_entries.feed_id AND ttrss_user_entries.last_read &gt; '2015-10-03' LEFT JOIN ttrss_entries ON ttrss_user_entries.ref_id = ttrss_entries.id LEFT JOIN ttrss_feed_categories ON ttrss_feeds.cat_id = ttrss_feed_categories.id WHERE ttrss_feeds.owner_uid = 2 GROUP BY feed, category ORDER BY items_day DESC failed: ERROR: division by zero

And second error:

Error: E_WARNING (2)
Filename:classes/db/pgsql.php:38    

Message: 
pg_query(): Query failed: ERROR: division by zero

Can you think of where there may be a problem please? Thank you.

**Comment by jsoares** [comment]
Thanks for the report. It should be fixed in the latest commit, but let me know if you still have issues.

**Comment by mr-flibble** [comment]
Thank you, you are the best :-)  Really.
Problem solved

PS: sorry for the spam, but I really felt the need to thank you.
