### ISSUE TITLE
PDO is coming

### ISSUE THREAD

**Issue by mr-flibble** [jsoares/ttrss-plugin-feedstatistics#2]
Hello, thanks for plugin.
Today I did update after TTRSS PDO update ( https://discourse.tt-rss.org/t/pdo-is-coming-heres-what-you-need-to-know/689 ) (from TTRSS 17.4 to 17.12)

And when I refresh statistics, I get this error in Error log:

```
Legacy connect requested to pgsql1.
1. classes/db.php(22): user_error(Legacy connect requested to pgsql, 1024)
2. classes/db.php(89): legacy_connect()
3. include/db.php(8): get()
4. plugins/feedstatistics/init.php(27): db_query(SELECT value FROM ttrss_user_prefs
WHERE pref_name = 'PURGE_OLD_DAYS' AND owner_uid = 2 AND profile IS NULL)
5. classes/pluginhost.php(120): hook_prefs_tab(prefFeeds)
6. classes/pref/feeds.php(1350): run_hooks(3, hook_prefs_tab, prefFeeds)
7. backend.php(123): index()
```

![image](https://user-images.githubusercontent.com/5197625/35194012-fd83d236-feab-11e7-89cc-aaf7383978a6.png)

Can you please look at this sometimes ? Thank you:)

**Comment by jsoares** [comment]
Hi, and thanks for the heads up; I don't really keep close track of core changes. I just switched the database queries to PDO. It seems to be working fine on MySQL, but please let me know if you find any issues.

My instance seems to have a problem (not plugin-related) where new unread articles are being time stamped as published and marked on import, leading to the plugin displaying absurd numbers. I'm trying to figure out whether it's something specific to my set-up.

**Comment by mr-flibble** [comment]
Hello, thanks for fast update!:)
I just did update and statistics are now blank :(

This is now in error log:
```
1. plugins/feedstatistics/init.php(72): execute(Array)
2. classes/pluginhost.php(120): hook_prefs_tab(prefFeeds)
3. classes/pref/feeds.php(1350): run_hooks(3, hook_prefs_tab, prefFeeds)
4. backend.php(123): index()

PDOStatement::execute(): SQLSTATE[42803]: Grouping error: 7 ERROR: column
 &quot;ttrss_feed_categories.title&quot;
must appear in the GROUP BY clause or be used in an aggregate function LINE 3: ttrss_feed_categories.title AS category, 
```


The error at the bottom of the list is notice before update 
![image](https://user-images.githubusercontent.com/5197625/35274604-f77b4a1c-003c-11e8-83de-c383a09f3a95.png)

**Comment by jsoares** [comment]
Here's to resurrecting old bugs. Sorry about that, should be fixed now. Cheers.

**Comment by mr-flibble** [comment]
Thanks, but still same problem, statistics is blank. :/

```
PDOStatement::execute(): SQLSTATE[42702]: Ambiguous column:
 7 ERROR: column reference &quot;id&quot; is ambiguous LINE 14: GROUP BY id, title, category ^


1. plugins/feedstatistics/init.php(73): execute(Array)
2. classes/pluginhost.php(120): hook_prefs_tab(prefFeeds)
3. classes/pref/feeds.php(1350): run_hooks(3, hook_prefs_tab, prefFeeds)
4. backend.php(123): index
```

![image](https://user-images.githubusercontent.com/5197625/35297983-fec9fb4e-0080-11e8-992a-ef286d2702ca.png)

**Comment by jsoares** [comment]
I should really get a pgsql instance for testing. Could you give it another go?

**Comment by mr-flibble** [comment]
Thanks! :-)
Stats now working again and there is no error in log.
You are the best! :)

**Comment by jsoares** [comment]
You're most welcome. Thanks for testing.
